"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-10-09 17:48:02.021132

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "airports",
        sa.Column("iata", sa.String(length=3), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=80), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.CheckConstraint("iata ~ '^[A-Z]{3}$'", name=op.f("ck_airports_iata_format")),
        sa.CheckConstraint("latitude BETWEEN -90 AND 90", name=op.f("ck_airports_lat_range")),
        sa.CheckConstraint("longitude BETWEEN -180 AND 180", name=op.f("ck_airports_lon_range")),
        sa.PrimaryKeyConstraint("iata", name=op.f("pk_airports")),
    )
    op.create_table(
        "background_job_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_name", sa.String(length=60), nullable=False),
        sa.Column("celery_task_id", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "success",
                "failed",
                "skipped",
                name="job_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_background_job_logs")),
    )
    op.create_index(
        "ix_background_job_logs_name_started",
        "background_job_logs",
        ["job_name", "started_at"],
        unique=False,
    )
    op.create_table(
        "flight_searches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("cache_key", sa.String(length=160), nullable=False),
        sa.Column("origin_iata", sa.String(length=3), nullable=False),
        sa.Column("destination_iata", sa.String(length=3), nullable=False),
        sa.Column("departure_date", sa.Date(), nullable=False),
        sa.Column("return_date", sa.Date(), nullable=False),
        sa.Column("adults", sa.Integer(), nullable=False),
        sa.Column(
            "cabin_class",
            sa.Enum(
                "economy",
                "premium_economy",
                "business",
                "first",
                name="flight_search_cabin",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("max_connections", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "success",
                "no_results",
                "failed",
                name="flight_search_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("searched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("is_mock", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flight_searches")),
    )
    op.create_index(
        "ix_flight_searches_cache_key",
        "flight_searches",
        ["cache_key", "searched_at"],
        unique=False,
    )
    op.create_index(
        "ix_flight_searches_searched_at", "flight_searches", ["searched_at"], unique=False
    )
    op.create_table(
        "forecast_sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("wave_model", sa.String(length=60), nullable=True),
        sa.Column("atmosphere_model", sa.String(length=60), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("attribution", sa.Text(), nullable=False),
        sa.Column("license_notes", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecast_sources")),
        sa.UniqueConstraint("code", name=op.f("uq_forecast_sources_code")),
    )
    op.create_table(
        "surf_spots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("country", sa.String(length=80), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("region", sa.String(length=120), nullable=False),
        sa.Column("region_group", sa.String(length=60), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("forecast_latitude", sa.Float(), nullable=False),
        sa.Column("forecast_longitude", sa.Float(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "break_type",
            sa.Enum(
                "reef",
                "point",
                "beach",
                "rivermouth",
                "slab",
                name="spot_break_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("wave_direction", sa.String(length=8), nullable=False),
        sa.Column("is_big_wave", sa.Boolean(), nullable=False),
        sa.Column("swell_window_min", sa.Float(), nullable=False),
        sa.Column("swell_window_max", sa.Float(), nullable=False),
        sa.Column("optimal_swell_direction_min", sa.Float(), nullable=False),
        sa.Column("optimal_swell_direction_max", sa.Float(), nullable=False),
        sa.Column("offshore_wind_direction", sa.Float(), nullable=False),
        sa.Column("min_swell_period_s", sa.Float(), nullable=False),
        sa.Column("ideal_swell_period_s", sa.Float(), nullable=False),
        sa.Column(
            "tide_preference",
            sa.Enum(
                "low",
                "low_to_mid",
                "mid",
                "mid_to_high",
                "high",
                "all",
                name="spot_tide_preference",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("wave_height_min_ft", sa.Float(), nullable=False),
        sa.Column("wave_height_max_ft", sa.Float(), nullable=False),
        sa.Column("height_factor", sa.Float(), nullable=False),
        sa.Column("calibration", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "skill_level",
            sa.Enum(
                "beginner",
                "intermediate",
                "advanced",
                "expert",
                name="spot_skill_level",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "best_months",
            sa.ARRAY(sa.Integer()),
            server_default=sa.text("'{}'::integer[]"),
            nullable=False,
        ),
        sa.Column("seasonality", sa.Text(), nullable=False),
        sa.Column("accessibility_notes", sa.Text(), nullable=False),
        sa.Column("hazards", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "forecast_latitude BETWEEN -90 AND 90", name=op.f("ck_surf_spots_flat_range")
        ),
        sa.CheckConstraint(
            "forecast_longitude BETWEEN -180 AND 180", name=op.f("ck_surf_spots_flon_range")
        ),
        sa.CheckConstraint(
            "height_factor > 0 AND height_factor <= 3", name=op.f("ck_surf_spots_height_factor")
        ),
        sa.CheckConstraint("latitude BETWEEN -90 AND 90", name=op.f("ck_surf_spots_lat_range")),
        sa.CheckConstraint("longitude BETWEEN -180 AND 180", name=op.f("ck_surf_spots_lon_range")),
        sa.CheckConstraint(
            "min_swell_period_s <= ideal_swell_period_s", name=op.f("ck_surf_spots_period_order")
        ),
        sa.CheckConstraint(
            "swell_window_min >= 0 AND swell_window_min < 360 AND swell_window_max >= 0 AND swell_window_max < 360 AND optimal_swell_direction_min >= 0 AND optimal_swell_direction_min < 360 AND optimal_swell_direction_max >= 0 AND optimal_swell_direction_max < 360 AND offshore_wind_direction >= 0 AND offshore_wind_direction < 360",
            name=op.f("ck_surf_spots_direction_ranges"),
        ),
        sa.CheckConstraint(
            "wave_height_min_ft < wave_height_max_ft", name=op.f("ck_surf_spots_height_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_surf_spots")),
        sa.UniqueConstraint("slug", name=op.f("uq_surf_spots_slug")),
    )
    op.create_index("ix_surf_spots_country_code", "surf_spots", ["country_code"], unique=False)
    op.create_index("ix_surf_spots_region_group", "surf_spots", ["region_group"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_users_email_lowercase")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "flight_offers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("flight_search_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_offer_id", sa.String(length=255), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("price_per_traveler", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("airlines", sa.ARRAY(sa.String(length=3)), nullable=False),
        sa.Column("airline_names", sa.ARRAY(sa.String(length=120)), nullable=False),
        sa.Column("origin_iata", sa.String(length=3), nullable=False),
        sa.Column("destination_iata", sa.String(length=3), nullable=False),
        sa.Column("outbound_departure_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("outbound_arrival_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("outbound_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("outbound_stops", sa.Integer(), nullable=False),
        sa.Column("inbound_departure_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("inbound_arrival_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("inbound_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("inbound_stops", sa.Integer(), nullable=False),
        sa.Column("origin_timezone", sa.String(length=64), nullable=False),
        sa.Column("destination_timezone", sa.String(length=64), nullable=False),
        sa.Column("segments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("baggage", sa.String(length=255), nullable=True),
        sa.Column("booking_url", sa.Text(), nullable=True),
        sa.Column("offer_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("quoted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "validation_status",
            sa.Enum(
                "unvalidated",
                "valid",
                "price_changed",
                "unavailable",
                name="offer_validation",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_mock", sa.Boolean(), nullable=False),
        sa.Column("provider_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint("total_price >= 0", name=op.f("ck_flight_offers_price_positive")),
        sa.ForeignKeyConstraint(
            ["flight_search_id"],
            ["flight_searches.id"],
            name=op.f("fk_flight_offers_flight_search_id_flight_searches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flight_offers")),
        sa.UniqueConstraint(
            "flight_search_id",
            "provider_offer_id",
            name=op.f("uq_flight_offers_flight_search_id_provider_offer_id"),
        ),
    )
    op.create_index(
        "ix_flight_offers_search_price",
        "flight_offers",
        ["flight_search_id", "total_price"],
        unique=False,
    )
    op.create_table(
        "forecast_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("run_key", sa.String(length=120), nullable=False),
        sa.Column("wave_model_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("atmosphere_model_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "success",
                "partial",
                "failed",
                name="forecast_run_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("spot_count", sa.Integer(), nullable=False),
        sa.Column("record_count", sa.Integer(), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("predictions_computed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["forecast_sources.id"],
            name=op.f("fk_forecast_runs_source_id_forecast_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecast_runs")),
        sa.UniqueConstraint(
            "source_id", "run_key", name=op.f("uq_forecast_runs_source_id_run_key")
        ),
    )
    op.create_index(
        "ix_forecast_runs_source_status",
        "forecast_runs",
        ["source_id", "status", "completed_at"],
        unique=False,
    )
    op.create_table(
        "notification_preferences",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("email_enabled", sa.Boolean(), nullable=False),
        sa.Column("sms_enabled", sa.Boolean(), nullable=False),
        sa.Column("all_paused", sa.Boolean(), nullable=False),
        sa.Column("phone_number", sa.String(length=16), nullable=True),
        sa.Column("phone_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sms_opt_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sms_opted_out_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("phone_verification_code_hash", sa.String(length=64), nullable=True),
        sa.Column("phone_verification_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("phone_verification_attempts", sa.Integer(), nullable=False),
        sa.Column("unsubscribe_token", sa.String(length=64), nullable=False),
        sa.Column("max_alerts_per_day", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "phone_number IS NULL OR phone_number ~ '^\\+[1-9][0-9]{6,14}$'",
            name=op.f("ck_notification_preferences_phone_e164"),
        ),
        sa.CheckConstraint(
            "max_alerts_per_day BETWEEN 1 AND 100",
            name=op.f("ck_notification_preferences_max_alerts_range"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notification_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_notification_preferences")),
        sa.UniqueConstraint(
            "unsubscribe_token", name=op.f("uq_notification_preferences_unsubscribe_token")
        ),
    )
    op.create_table(
        "saved_searches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "paused",
                name="search_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "date_mode",
            sa.Enum(
                "fixed",
                "flexible",
                name="search_date_mode",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("date_start", sa.Date(), nullable=True),
        sa.Column("date_end", sa.Date(), nullable=True),
        sa.Column("horizon_days", sa.Integer(), nullable=False),
        sa.Column("wave_min_ft", sa.Float(), nullable=False),
        sa.Column("wave_max_ft", sa.Float(), nullable=False),
        sa.Column("wave_preferred_ft", sa.Float(), nullable=True),
        sa.Column("units", sa.String(length=2), nullable=False),
        sa.Column(
            "min_quality",
            sa.Enum(
                "poor",
                "fair",
                "good",
                "very_good",
                "excellent",
                "exceptional",
                name="search_min_quality",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("min_period_s", sa.Float(), nullable=True),
        sa.Column("max_wind_kmh", sa.Float(), nullable=True),
        sa.Column(
            "wind_requirement",
            sa.Enum(
                "any",
                "not_onshore",
                "offshore",
                name="search_wind_requirement",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("swell_direction_min", sa.Float(), nullable=True),
        sa.Column("swell_direction_max", sa.Float(), nullable=True),
        sa.Column("min_consistency", sa.Integer(), nullable=True),
        sa.Column(
            "break_types",
            sa.ARRAY(sa.String(length=16)),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column("min_window_hours", sa.Integer(), nullable=False),
        sa.Column(
            "destination_mode",
            sa.Enum(
                "all",
                "regions",
                "spots",
                name="search_destination_mode",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("max_transfer_minutes", sa.Integer(), nullable=True),
        sa.Column("max_origin_ground_km", sa.Integer(), nullable=False),
        sa.Column(
            "notification_channel",
            sa.Enum(
                "email",
                "sms",
                "both",
                "dashboard",
                name="search_notification_channel",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("notify_surf_only", sa.Boolean(), nullable=False),
        sa.Column("notify_on_updates", sa.Boolean(), nullable=False),
        sa.Column(
            "priority",
            sa.Enum(
                "balanced",
                "best_waves",
                "cheapest",
                "shortest",
                name="search_priority",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("paused_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_evaluated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "date_mode <> 'fixed' OR (date_start IS NOT NULL AND date_end IS NOT NULL AND date_end >= date_start)",
            name=op.f("ck_saved_searches_fixed_dates"),
        ),
        sa.CheckConstraint(
            "horizon_days BETWEEN 1 AND 365", name=op.f("ck_saved_searches_horizon_range")
        ),
        sa.CheckConstraint(
            "min_window_hours BETWEEN 1 AND 240", name=op.f("ck_saved_searches_window_hours")
        ),
        sa.CheckConstraint(
            "wave_min_ft >= 0 AND wave_min_ft < wave_max_ft",
            name=op.f("ck_saved_searches_wave_range"),
        ),
        sa.CheckConstraint(
            "wave_preferred_ft IS NULL OR (wave_preferred_ft >= wave_min_ft AND wave_preferred_ft <= wave_max_ft)",
            name=op.f("ck_saved_searches_wave_preferred"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_saved_searches_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_searches")),
    )
    op.create_index(
        "ix_saved_searches_user_status", "saved_searches", ["user_id", "status"], unique=False
    )
    op.create_table(
        "spot_airports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("spot_id", sa.Integer(), nullable=False),
        sa.Column("airport_iata", sa.String(length=3), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("transfer_minutes", sa.Integer(), nullable=False),
        sa.Column("transfer_mode", sa.String(length=32), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "transfer_minutes >= 0", name=op.f("ck_spot_airports_transfer_positive")
        ),
        sa.ForeignKeyConstraint(
            ["airport_iata"],
            ["airports.iata"],
            name=op.f("fk_spot_airports_airport_iata_airports"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["spot_id"],
            ["surf_spots.id"],
            name=op.f("fk_spot_airports_spot_id_surf_spots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_spot_airports")),
        sa.UniqueConstraint(
            "spot_id", "airport_iata", name=op.f("uq_spot_airports_spot_id_airport_iata")
        ),
    )
    op.create_index(
        "uq_spot_airports_one_primary",
        "spot_airports",
        ["spot_id"],
        unique=True,
        postgresql_where=sa.text("is_primary"),
    )
    op.create_table(
        "user_airports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("airport_iata", sa.String(length=3), nullable=False),
        sa.Column("label", sa.String(length=60), nullable=True),
        sa.Column("is_home", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["airport_iata"],
            ["airports.iata"],
            name=op.f("fk_user_airports_airport_iata_airports"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_airports_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_airports")),
        sa.UniqueConstraint(
            "user_id", "airport_iata", name=op.f("uq_user_airports_user_id_airport_iata")
        ),
    )
    op.create_index(op.f("ix_user_airports_user_id"), "user_airports", ["user_id"], unique=False)
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("home_airport", sa.String(length=3), nullable=True),
        sa.Column("home_city", sa.String(length=120), nullable=True),
        sa.Column("preferred_wave_min_ft", sa.Float(), nullable=True),
        sa.Column("preferred_wave_max_ft", sa.Float(), nullable=True),
        sa.Column(
            "preferred_break_type",
            sa.Enum(
                "reef",
                "point",
                "beach",
                "rivermouth",
                "slab",
                name="profile_break_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "experience_level",
            sa.Enum(
                "beginner",
                "intermediate",
                "advanced",
                "expert",
                name="profile_skill_level",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("units", sa.String(length=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "preferred_wave_min_ft IS NULL OR preferred_wave_max_ft IS NULL OR preferred_wave_min_ft <= preferred_wave_max_ft",
            name=op.f("ck_user_profiles_wave_range"),
        ),
        sa.ForeignKeyConstraint(
            ["home_airport"],
            ["airports.iata"],
            name=op.f("fk_user_profiles_home_airport_airports"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_profiles")),
    )
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_user_sessions_token_hash")),
    )
    op.create_index("ix_user_sessions_expires_at", "user_sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    op.create_table(
        "user_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "email_verify",
                "password_reset",
                name="token_purpose",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_user_tokens_token_hash")),
    )
    op.create_index(
        "ix_user_tokens_user_purpose", "user_tokens", ["user_id", "purpose"], unique=False
    )
    op.create_table(
        "search_destinations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("search_id", sa.Uuid(), nullable=False),
        sa.Column("spot_id", sa.Integer(), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("region_group", sa.String(length=60), nullable=True),
        sa.CheckConstraint(
            "(spot_id IS NOT NULL)::int + (country_code IS NOT NULL)::int + (region_group IS NOT NULL)::int = 1",
            name=op.f("ck_search_destinations_exactly_one_target"),
        ),
        sa.ForeignKeyConstraint(
            ["search_id"],
            ["saved_searches.id"],
            name=op.f("fk_search_destinations_search_id_saved_searches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["spot_id"],
            ["surf_spots.id"],
            name=op.f("fk_search_destinations_spot_id_surf_spots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_destinations")),
    )
    op.create_index(
        "ix_search_destinations_search", "search_destinations", ["search_id"], unique=False
    )
    op.create_table(
        "search_origins",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("search_id", sa.Uuid(), nullable=False),
        sa.Column("airport_iata", sa.String(length=3), nullable=False),
        sa.ForeignKeyConstraint(
            ["airport_iata"],
            ["airports.iata"],
            name=op.f("fk_search_origins_airport_iata_airports"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["search_id"],
            ["saved_searches.id"],
            name=op.f("fk_search_origins_search_id_saved_searches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_origins")),
        sa.UniqueConstraint(
            "search_id", "airport_iata", name=op.f("uq_search_origins_search_id_airport_iata")
        ),
    )
    op.create_table(
        "swell_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("spot_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "downgraded",
                "cancelled",
                "passed",
                name="swell_event_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("peak_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("peak_score", sa.Integer(), nullable=False),
        sa.Column("avg_score", sa.Float(), nullable=False),
        sa.Column(
            "peak_label",
            sa.Enum(
                "poor",
                "fair",
                "good",
                "very_good",
                "excellent",
                "exceptional",
                name="event_quality_label",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("peak_breaking_height_min_ft", sa.Float(), nullable=False),
        sa.Column("peak_breaking_height_max_ft", sa.Float(), nullable=False),
        sa.Column("peak_swell_height_m", sa.Float(), nullable=True),
        sa.Column("peak_swell_period_s", sa.Float(), nullable=True),
        sa.Column("peak_swell_direction_deg", sa.Float(), nullable=True),
        sa.Column("peak_wind_speed_kmh", sa.Float(), nullable=True),
        sa.Column("peak_wind_direction_deg", sa.Float(), nullable=True),
        sa.Column("peak_wind_relation", sa.String(length=16), nullable=False),
        sa.Column("qualifying_hours", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column(
            "confidence_label",
            sa.Enum(
                "low",
                "moderate",
                "high",
                name="event_confidence_label",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("latest_run_id", sa.Integer(), nullable=True),
        sa.Column("source_code", sa.String(length=40), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("first_detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("history", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("merged_into_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint("end_time >= start_time", name=op.f("ck_swell_events_time_order")),
        sa.ForeignKeyConstraint(
            ["latest_run_id"],
            ["forecast_runs.id"],
            name=op.f("fk_swell_events_latest_run_id_forecast_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["merged_into_id"],
            ["swell_events.id"],
            name=op.f("fk_swell_events_merged_into_id_swell_events"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["spot_id"],
            ["surf_spots.id"],
            name=op.f("fk_swell_events_spot_id_surf_spots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_swell_events")),
    )
    op.create_index(
        "ix_swell_events_spot_start", "swell_events", ["spot_id", "start_time"], unique=False
    )
    op.create_index(
        "ix_swell_events_status_start", "swell_events", ["status", "start_time"], unique=False
    )
    op.create_table(
        "travel_preferences",
        sa.Column("search_id", sa.Uuid(), nullable=False),
        sa.Column("max_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("direct_only", sa.Boolean(), nullable=False),
        sa.Column("max_layovers", sa.Integer(), nullable=False),
        sa.Column("max_flight_hours", sa.Float(), nullable=False),
        sa.Column("min_days_at_destination", sa.Integer(), nullable=False),
        sa.Column("max_trip_days", sa.Integer(), nullable=False),
        sa.Column("travelers", sa.Integer(), nullable=False),
        sa.Column(
            "preferred_airlines",
            sa.ARRAY(sa.String(length=2)),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column(
            "cabin_class",
            sa.Enum(
                "economy",
                "premium_economy",
                "business",
                "first",
                name="travel_cabin_class",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("arrival_buffer_days", sa.Integer(), nullable=False),
        sa.Column("departure_buffer_days", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "currency ~ '^[A-Z]{3}$'", name=op.f("ck_travel_preferences_currency_format")
        ),
        sa.CheckConstraint(
            "arrival_buffer_days BETWEEN 0 AND 14",
            name=op.f("ck_travel_preferences_arrival_buffer"),
        ),
        sa.CheckConstraint(
            "departure_buffer_days BETWEEN 0 AND 14",
            name=op.f("ck_travel_preferences_departure_buffer"),
        ),
        sa.CheckConstraint(
            "max_layovers BETWEEN 0 AND 3", name=op.f("ck_travel_preferences_layovers_range")
        ),
        sa.CheckConstraint("max_price > 0", name=op.f("ck_travel_preferences_price_positive")),
        sa.CheckConstraint(
            "max_trip_days >= min_days_at_destination", name=op.f("ck_travel_preferences_trip_days")
        ),
        sa.CheckConstraint(
            "min_days_at_destination >= 1", name=op.f("ck_travel_preferences_min_days")
        ),
        sa.CheckConstraint(
            "travelers BETWEEN 1 AND 9", name=op.f("ck_travel_preferences_travelers_range")
        ),
        sa.ForeignKeyConstraint(
            ["search_id"],
            ["saved_searches.id"],
            name=op.f("fk_travel_preferences_search_id_saved_searches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("search_id", name=op.f("pk_travel_preferences")),
    )
    op.create_table(
        "wave_forecasts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("spot_id", sa.Integer(), nullable=False),
        sa.Column("valid_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sig_wave_height_m", sa.Float(), nullable=True),
        sa.Column("wave_period_s", sa.Float(), nullable=True),
        sa.Column("wave_direction_deg", sa.Float(), nullable=True),
        sa.Column("primary_swell_height_m", sa.Float(), nullable=True),
        sa.Column("primary_swell_period_s", sa.Float(), nullable=True),
        sa.Column("primary_swell_direction_deg", sa.Float(), nullable=True),
        sa.Column("secondary_swell_height_m", sa.Float(), nullable=True),
        sa.Column("secondary_swell_period_s", sa.Float(), nullable=True),
        sa.Column("secondary_swell_direction_deg", sa.Float(), nullable=True),
        sa.Column("wind_wave_height_m", sa.Float(), nullable=True),
        sa.Column("wind_wave_period_s", sa.Float(), nullable=True),
        sa.Column("wind_wave_direction_deg", sa.Float(), nullable=True),
        sa.Column("wind_speed_kmh", sa.Float(), nullable=True),
        sa.Column("wind_direction_deg", sa.Float(), nullable=True),
        sa.Column("wind_gust_kmh", sa.Float(), nullable=True),
        sa.Column("pressure_msl_hpa", sa.Float(), nullable=True),
        sa.Column("sea_level_m", sa.Float(), nullable=True),
        sa.Column("wave_power_kw_m", sa.Float(), nullable=True),
        sa.Column("missing_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "sig_wave_height_m IS NULL OR sig_wave_height_m >= 0",
            name=op.f("ck_wave_forecasts_hs_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["forecast_runs.id"],
            name=op.f("fk_wave_forecasts_run_id_forecast_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["spot_id"],
            ["surf_spots.id"],
            name=op.f("fk_wave_forecasts_spot_id_surf_spots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wave_forecasts")),
        sa.UniqueConstraint(
            "run_id",
            "spot_id",
            "valid_time",
            name=op.f("uq_wave_forecasts_run_id_spot_id_valid_time"),
        ),
    )
    op.create_index(
        "ix_wave_forecasts_spot_valid", "wave_forecasts", ["spot_id", "valid_time"], unique=False
    )
    op.create_table(
        "opportunity_matches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("search_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("swell_event_id", sa.Uuid(), nullable=False),
        sa.Column("spot_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending_flights",
                "flight_found",
                "surf_only",
                "expired",
                "dismissed",
                name="match_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("status_reason", sa.Text(), nullable=True),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("qualifying_hours", sa.Integer(), nullable=False),
        sa.Column("peak_score", sa.Integer(), nullable=False),
        sa.Column("avg_score", sa.Float(), nullable=False),
        sa.Column(
            "peak_label",
            sa.Enum(
                "poor",
                "fair",
                "good",
                "very_good",
                "excellent",
                "exceptional",
                name="match_quality_label",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("breaking_height_min_ft", sa.Float(), nullable=False),
        sa.Column("breaking_height_max_ft", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column(
            "confidence_label",
            sa.Enum(
                "low",
                "moderate",
                "high",
                name="match_confidence_label",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("destination_iata", sa.String(length=3), nullable=True),
        sa.Column("transfer_minutes", sa.Integer(), nullable=True),
        sa.Column("recommended_arrival_date", sa.Date(), nullable=True),
        sa.Column("recommended_departure_date", sa.Date(), nullable=True),
        sa.Column("best_offer_id", sa.Uuid(), nullable=True),
        sa.Column("best_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("origin_iata", sa.String(length=3), nullable=True),
        sa.Column("scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("overall_score", sa.Integer(), nullable=False),
        sa.Column("flight_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("flight_search_error", sa.Text(), nullable=True),
        sa.Column("flights_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_notified_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("notification_count", sa.Integer(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "window_end >= window_start", name=op.f("ck_opportunity_matches_window_order")
        ),
        sa.ForeignKeyConstraint(
            ["best_offer_id"],
            ["flight_offers.id"],
            name=op.f("fk_opportunity_matches_best_offer_id_flight_offers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["search_id"],
            ["saved_searches.id"],
            name=op.f("fk_opportunity_matches_search_id_saved_searches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["spot_id"],
            ["surf_spots.id"],
            name=op.f("fk_opportunity_matches_spot_id_surf_spots"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["swell_event_id"],
            ["swell_events.id"],
            name=op.f("fk_opportunity_matches_swell_event_id_swell_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_opportunity_matches_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunity_matches")),
        sa.UniqueConstraint(
            "search_id",
            "swell_event_id",
            name=op.f("uq_opportunity_matches_search_id_swell_event_id"),
        ),
    )
    op.create_index(
        "ix_opportunity_matches_status_checked",
        "opportunity_matches",
        ["status", "flight_checked_at"],
        unique=False,
    )
    op.create_index(
        "ix_opportunity_matches_user_status",
        "opportunity_matches",
        ["user_id", "status"],
        unique=False,
    )
    op.create_table(
        "surf_quality_predictions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("forecast_id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("spot_id", sa.Integer(), nullable=False),
        sa.Column("valid_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_daylight", sa.Boolean(), nullable=False),
        sa.Column("breaking_height_min_ft", sa.Float(), nullable=False),
        sa.Column("breaking_height_max_ft", sa.Float(), nullable=False),
        sa.Column("breaking_height_method", sa.String(length=40), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column(
            "label",
            sa.Enum(
                "poor",
                "fair",
                "good",
                "very_good",
                "excellent",
                "exceptional",
                name="prediction_quality_label",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("components", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("wind_relation", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column(
            "confidence_label",
            sa.Enum(
                "low",
                "moderate",
                "high",
                name="prediction_confidence_label",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 100",
            name=op.f("ck_surf_quality_predictions_confidence_range"),
        ),
        sa.CheckConstraint(
            "score BETWEEN 0 AND 100", name=op.f("ck_surf_quality_predictions_score_range")
        ),
        sa.ForeignKeyConstraint(
            ["forecast_id"],
            ["wave_forecasts.id"],
            name=op.f("fk_surf_quality_predictions_forecast_id_wave_forecasts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["forecast_runs.id"],
            name=op.f("fk_surf_quality_predictions_run_id_forecast_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["spot_id"],
            ["surf_spots.id"],
            name=op.f("fk_surf_quality_predictions_spot_id_surf_spots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_surf_quality_predictions")),
        sa.UniqueConstraint("forecast_id", name=op.f("uq_surf_quality_predictions_forecast_id")),
    )
    op.create_index(
        "ix_surf_quality_predictions_run", "surf_quality_predictions", ["run_id"], unique=False
    )
    op.create_index(
        "ix_surf_quality_predictions_spot_valid",
        "surf_quality_predictions",
        ["spot_id", "valid_time"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("match_id", sa.Uuid(), nullable=True),
        sa.Column(
            "channel",
            sa.Enum(
                "email",
                "sms",
                name="notification_channel",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "kind",
            sa.Enum(
                "new_opportunity",
                "improved",
                "price_drop",
                "schedule_change",
                "surf_only",
                name="notification_kind",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "sending",
                "sent",
                "failed",
                "skipped",
                name="notification_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("dedup_key", sa.String(length=200), nullable=False),
        sa.Column("recipient", sa.String(length=320), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=False),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("provider", sa.String(length=20), nullable=True),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["opportunity_matches.id"],
            name=op.f("fk_notifications_match_id_opportunity_matches"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint("dedup_key", name=op.f("uq_notifications_dedup_key")),
    )
    op.create_index(
        "ix_notifications_status_next", "notifications", ["status", "next_attempt_at"], unique=False
    )
    op.create_index(
        "ix_notifications_user_created", "notifications", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "opportunity_offers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.Uuid(), nullable=False),
        sa.Column("offer_id", sa.Uuid(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("price_converted", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["opportunity_matches.id"],
            name=op.f("fk_opportunity_offers_match_id_opportunity_matches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["offer_id"],
            ["flight_offers.id"],
            name=op.f("fk_opportunity_offers_offer_id_flight_offers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunity_offers")),
        sa.UniqueConstraint(
            "match_id", "offer_id", name=op.f("uq_opportunity_offers_match_id_offer_id")
        ),
    )

    # No two ACTIVE swell events may overlap in time at the same spot (duplicate guard).
    # DEFERRABLE so a detection pass can merge/shift events inside one transaction.
    op.execute(
        "ALTER TABLE swell_events ADD CONSTRAINT ex_swell_events_no_overlap "
        "EXCLUDE USING gist (spot_id WITH =, tstzrange(start_time, end_time, '[]') WITH &&) "
        "WHERE (status = 'active') DEFERRABLE INITIALLY DEFERRED"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        "ALTER TABLE IF EXISTS swell_events DROP CONSTRAINT IF EXISTS ex_swell_events_no_overlap"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("opportunity_offers")
    op.drop_index("ix_notifications_user_created", table_name="notifications")
    op.drop_index("ix_notifications_status_next", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_surf_quality_predictions_spot_valid", table_name="surf_quality_predictions")
    op.drop_index("ix_surf_quality_predictions_run", table_name="surf_quality_predictions")
    op.drop_table("surf_quality_predictions")
    op.drop_index("ix_opportunity_matches_user_status", table_name="opportunity_matches")
    op.drop_index("ix_opportunity_matches_status_checked", table_name="opportunity_matches")
    op.drop_table("opportunity_matches")
    op.drop_index("ix_wave_forecasts_spot_valid", table_name="wave_forecasts")
    op.drop_table("wave_forecasts")
    op.drop_table("travel_preferences")
    op.drop_index("ix_swell_events_status_start", table_name="swell_events")
    op.drop_index("ix_swell_events_spot_start", table_name="swell_events")
    op.drop_table("swell_events")
    op.drop_table("search_origins")
    op.drop_index("ix_search_destinations_search", table_name="search_destinations")
    op.drop_table("search_destinations")
    op.drop_index("ix_user_tokens_user_purpose", table_name="user_tokens")
    op.drop_table("user_tokens")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_index("ix_user_sessions_expires_at", table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_table("user_profiles")
    op.drop_index(op.f("ix_user_airports_user_id"), table_name="user_airports")
    op.drop_table("user_airports")
    op.drop_index(
        "uq_spot_airports_one_primary",
        table_name="spot_airports",
        postgresql_where=sa.text("is_primary"),
    )
    op.drop_table("spot_airports")
    op.drop_index("ix_saved_searches_user_status", table_name="saved_searches")
    op.drop_table("saved_searches")
    op.drop_table("notification_preferences")
    op.drop_index("ix_forecast_runs_source_status", table_name="forecast_runs")
    op.drop_table("forecast_runs")
    op.drop_index("ix_flight_offers_search_price", table_name="flight_offers")
    op.drop_table("flight_offers")
    op.drop_table("users")
    op.drop_index("ix_surf_spots_region_group", table_name="surf_spots")
    op.drop_index("ix_surf_spots_country_code", table_name="surf_spots")
    op.drop_table("surf_spots")
    op.drop_table("forecast_sources")
    op.drop_index("ix_flight_searches_searched_at", table_name="flight_searches")
    op.drop_index("ix_flight_searches_cache_key", table_name="flight_searches")
    op.drop_table("flight_searches")
    op.drop_index("ix_background_job_logs_name_started", table_name="background_job_logs")
    op.drop_table("background_job_logs")
    op.drop_table("airports")
    # ### end Alembic commands ###
